-- DuoCouple baseline schema.
-- Apply this in the Supabase SQL editor, then add policies appropriate to your
-- authentication model before allowing production traffic.
-- Never use a service_role/secret key in the Android app.

create table if not exists public.user_profiles (
  id text primary key,
  name text not null,
  "avatarEmoji" text not null,
  "dailyBudget" double precision not null default 50.0,
  "monthlySavingGoal" double precision not null default 500.0
);

create table if not exists public.learning_roadmaps (
  id integer generated by default as identity primary key,
  "ownerId" text not null,
  title text not null,
  description text not null,
  "createdTimestamp" bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.roadmap_lessons (
  id integer generated by default as identity primary key,
  "roadmapId" integer not null references public.learning_roadmaps(id) on delete cascade,
  title text not null,
  description text not null,
  difficulty text not null,
  "isCompleted" boolean not null default false,
  "orderIndex" integer not null
);

create table if not exists public.learning_tasks (
  id integer generated by default as identity primary key,
  "ownerId" text not null,
  title text not null,
  "dateString" text not null,
  "isCompleted" boolean not null default false,
  "minutesSpent" integer not null default 0,
  timestamp bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.expense_entries (
  id integer generated by default as identity primary key,
  "ownerId" text not null,
  amount double precision not null,
  "isIncome" boolean not null,
  category text not null,
  "dateString" text not null,
  note text not null default '',
  timestamp bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.saving_tasks (
  id integer generated by default as identity primary key,
  "ownerId" text not null,
  title text not null,
  "rewardAmount" double precision not null,
  "dateString" text not null,
  "isCompleted" boolean not null default false,
  timestamp bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.calendar_tasks (
  id text primary key,
  title text not null,
  time text not null,
  "isCompleted" boolean not null default false,
  timestamp bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.user_accounts (
  email text primary key,
  name text,
  emoji text,
  created_at timestamptz not null default now()
);

create table if not exists public.device_status_telemetry (
  device_id text primary key,
  device_name text not null,
  cpu_usage double precision not null default 0,
  ram_usage double precision not null default 0,
  user_email text,
  updated_at timestamptz not null default now()
);

create index if not exists learning_roadmaps_owner_idx on public.learning_roadmaps ("ownerId");
create index if not exists learning_tasks_owner_date_idx on public.learning_tasks ("ownerId", "dateString");
create index if not exists expense_entries_owner_date_idx on public.expense_entries ("ownerId", "dateString");
create index if not exists saving_tasks_owner_date_idx on public.saving_tasks ("ownerId", "dateString");

-- Security checklist:
-- 1. Enable RLS on every table before production.
-- 2. Add authenticated-user policies that scope rows to auth.uid() or a
--    server-maintained couple membership table.
-- 3. Do not create unrestricted anon policies for private couple data.
-- 4. Restrict telemetry reads to an admin role or a protected server function.
-- 5. The current Android client has no Supabase Auth session yet; implement
--    Auth first, then enable policies that require authenticated access.
