import { createClient } from '@supabase/supabase-js';
import { injectSpeedInsights } from '@vercel/speed-insights';
import './style.css';

// Initialize Vercel Speed Insights
injectSpeedInsights();

const url = (import.meta.env.VITE_SUPABASE_URL || '').trim();
const key = (import.meta.env.VITE_SUPABASE_ANON_KEY || '').trim();
const supabase = url && key ? createClient(url, key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
const collections = [
  ['people', 'user_accounts', 'email', 'People', 'Registered mobile users', 'users'],
  ['couples', 'user_profiles', 'id', 'Couples', 'Shared relationship profiles', 'heart'],
  ['roadmaps', 'learning_roadmaps', 'id', 'Roadmaps', 'Learning plans', 'path'],
  ['tasks', 'learning_tasks', 'id', 'Tasks', 'Daily actions', 'check'],
  ['expenses', 'expense_entries', 'id', 'Expenses', 'Money entries', 'wallet'],
  ['savings', 'saving_tasks', 'id', 'Savings', 'Goals in motion', 'target'],
];
const icon = (name) => ({ users: '◌', heart: '♡', path: '⌁', check: '✓', wallet: '▣', target: '◎' }[name] || '•');
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const number = (value) => new Intl.NumberFormat('en-US').format(value);
const moduleFor = (hash) => collections.find(([slug]) => `#${slug}` === hash) || null;

function loginScreen(message = '') {
  document.querySelector('#app').innerHTML = `<main class="login-page"><div class="login-visual"><div class="mini-orbit"><span></span><b>DC</b></div><p class="eyebrow">DuoCouple / secure workspace</p><h1>Build a better<br><em>life together.</em></h1><p>One calm command center for your relationship, routines, money, and plans.</p></div><section class="login-card"><div class="brand"><img class="brand-logo" src="/duocouple-logo.png" alt="DuoCouple logo"><span><b>DuoCouple</b><small>Control room</small></span></div><p class="eyebrow">Welcome back</p><h2>Sign in to your dashboard</h2><p class="login-copy">Your private workspace is protected by Supabase Auth.</p>${message ? `<div class="error-box">${esc(message)}</div>` : ''}<form id="login-form"><label>Email<input id="email" type="email" autocomplete="username" required placeholder="you@example.com"></label><label>Password<input id="password" type="password" autocomplete="current-password" required minlength="6" placeholder="Your password"></label><button class="button primary" type="submit">Enter workspace <span>→</span></button></form><p class="login-foot">Need access? Ask your workspace administrator.</p></section></main>`;
  document.querySelector('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector('button'); button.disabled = true; button.textContent = 'Checking access…'; const { error } = await supabase.auth.signInWithPassword({ email: document.querySelector('#email').value.trim(), password: document.querySelector('#password').value }); if (error) return loginScreen(error.status === 429 ? 'Too many attempts. Please wait and try again.' : 'Invalid email or password.'); boot(); });
}

async function readCount(table, column) { const { count, error } = await supabase.from(table).select(column, { count: 'exact', head: true }); if (error) throw error; return count ?? 0; }
async function getCounts() { const results = await Promise.allSettled(collections.map(([, table, column]) => readCount(table, column))); return { values: results.map((r) => r.status === 'fulfilled' ? r.value : null), errors: results.map((r) => r.status === 'rejected' ? r.reason : null) }; }

function sidebar(active) { return `<aside class="sidebar"><div class="brand"><img class="brand-logo" src="/duocouple-logo.png" alt="DuoCouple logo"><span><b>DuoCouple</b><small>Control room</small></span></div><nav><a class="${active === 'overview' ? 'active' : ''}" href="#overview">Overview</a>${collections.map(([slug, , , label, , glyph]) => `<a class="${active === slug ? 'active' : ''}" href="#${slug}"><span>${icon(glyph)}</span>${label}</a>`).join('')}<a class="${active === 'security' ? 'active' : ''}" href="#security">Security</a></nav><div class="sidebar-bottom"><div class="connection"><span></span><div><b>Connected</b><small>Supabase + Vercel</small></div></div><button id="logout" class="text-button">Sign out</button></div></aside>`; }
function shell(active, content) { document.querySelector('#app').innerHTML = `<div class="app-shell">${sidebar(active)}<main class="dashboard">${content}</main></div>`; document.querySelector('#logout').addEventListener('click', async () => { await supabase.auth.signOut(); loginScreen(); }); }
function topbar(title, detail) { return `<header class="topbar"><div><p class="eyebrow">DuoCouple / Admin</p><h1>${title}</h1><p class="subtitle">${detail}</p></div><div class="top-actions"><span class="secure-pill">● Secure session</span><button class="button outline" id="refresh">↻ Refresh</button></div></header>`; }
function card(item, value, error) { const [slug, table, , label, description, glyph] = item; return `<a href="#${slug}" class="metric-card ${error ? 'metric-card-error' : ''}"><div class="metric-heading"><span class="metric-icon">${icon(glyph)}</span><span>${label}</span></div><strong>${value === null ? '—' : number(value)}</strong><p>${error ? 'Needs attention' : description}</p><small>${error ? esc(error.message || 'Check access and RLS policies.') : table}</small><span class="card-arrow">Open module →</span></a>`; }

async function renderOverview(data, user) {
  const total = data.values.reduce((sum, value) => sum + (Number.isFinite(value) ? value : 0), 0); const failed = data.errors.filter(Boolean).length;
  shell('overview', `${topbar('Your shared life, <em>in sync.</em>', 'Choose a module to inspect its data separately.')}${failed ? `<div class="notice"><b>${failed} module${failed === 1 ? '' : 's'} need attention</b><span>Open the affected module to see its Supabase error.</span></div>` : ''}<section class="overview-grid"><div class="welcome-card"><div><p class="eyebrow">Control room</p><h2>Everything has<br><em>its own space.</em></h2><p>Use the navigation to open People, Couples, Learning, Money, or Savings. Each module loads independently so the dashboard stays clear and useful.</p></div><div class="orbit-art"><div class="orbit-ring ring-one"></div><div class="orbit-ring ring-two"></div><div class="orbit-core">D<span>+</span>C</div></div></div><div class="summary-card"><p class="eyebrow">Total records</p><strong>${number(total)}</strong><p class="muted">Across all connected collections</p><small>${esc(user.email || '')}</small></div></section><section class="module-section"><div class="section-heading"><div><p class="eyebrow">Modules</p><h2>Choose what to inspect</h2></div><span class="muted">${collections.length} separate views</span></div><div class="module-grid">${collections.map((item, i) => card(item, data.values[i], data.errors[i])).join('')}</div></section>`);
  document.querySelector('#refresh').onclick = async () => { document.querySelector('#refresh').textContent = '↻ Loading…'; await renderOverview(await getCounts(), user); };
}

async function loadUsers() { const target = document.querySelector('#users-result'); const button = document.querySelector('#load-users'); button.disabled = true; button.textContent = 'Loading…'; const { data: { session } } = await supabase.auth.getSession(); const response = await fetch('/api/users', { headers: { Authorization: `Bearer ${session?.access_token || ''}` } }); const body = await response.json().catch(() => ({})); button.disabled = false; button.textContent = 'Refresh people'; if (!response.ok) { target.innerHTML = `<div class="users-error"><b>${response.status === 403 ? 'Admin permission required' : 'Could not load people'}</b><p>${esc(body.error || 'The protected endpoint rejected this request.')}</p></div>`; return; } target.innerHTML = `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Created</th><th>Last sign-in</th></tr></thead><tbody>${body.users.map((item) => `<tr><td><b>${esc(item.name || 'Unnamed user')}</b></td><td>${esc(item.email || '—')}</td><td><span class="status ${item.confirmed ? 'confirmed' : ''}">${item.confirmed ? 'Confirmed' : 'Unconfirmed'}</span></td><td>${esc(item.created_at ? new Date(item.created_at).toLocaleDateString() : '—')}</td><td>${esc(item.last_sign_in_at ? new Date(item.last_sign_in_at).toLocaleString() : 'Never')}</td></tr>`).join('')}</tbody></table></div>`; }

async function renderModule(item, value, error, user) { const [slug, table, , label, description, glyph] = item; const body = slug === 'people' ? `<div class="people-panel"><div class="section-heading"><div><p class="eyebrow">${label} module</p><h2>Registered mobile users</h2><p class="muted">Name, email, status, and activity from the mobile application.</p></div><button class="button outline" id="load-users">Load users</button></div><div id="users-result" class="users-result"><div class="empty-state">Select “Load users” to fetch the protected user list.</div></div></div>` : `<div class="detail-card"><div class="detail-icon">${icon(glyph)}</div><p class="eyebrow">${label} module</p><h2>${description}</h2><strong>${error ? '—' : number(value)}</strong><p class="muted">This module is intentionally separate from the overview. Connect the mobile feature to populate and inspect ${table} records here.</p><div class="empty-state">No detailed records are displayed until this module is opened and its data is available.</div></div>`; shell(slug, `${topbar(`${label} <em>module.</em>`, `Inspect ${description.toLowerCase()} independently.`)}${error ? `<div class="notice"><b>Supabase needs attention</b><span>${esc(error.message || 'Check table access and RLS policies.')}</span></div>` : ''}${body}`); if (slug === 'people') document.querySelector('#load-users').addEventListener('click', loadUsers); }

async function renderRoute(user) { const data = await getCounts(); const item = moduleFor(window.location.hash); if (!item) return renderOverview(data, user); const index = collections.indexOf(item); return renderModule(item, data.values[index], data.errors[index], user); }
async function boot() { if (!supabase) return loginScreen('The dashboard is not configured. Add the Supabase public variables in Vercel.'); const { data: { session } } = await supabase.auth.getSession(); if (!session) return loginScreen(); await renderRoute(session.user); window.onhashchange = () => renderRoute(session.user); supabase.auth.onAuthStateChange((_event, next) => { if (!next) loginScreen(); }); }
boot();
